version: '3.1'
services:
  video-streaming:
    container_name: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    environment:
      - APP_PORT=8080
      - VIDEO_STORAGE_HOST=storage-streaming
      - VIDEO_STORAGE_PORT=8080
      - DB_URL=mongodb://db:27017
      - DB_NAME=flixtube
    volumes:
      - ./video-streaming:/app/
    depends_on:
      - db
    ports:
      - "8080:8080"
  storage-streaming:
    container_name: storage-streaming
    build:
      context: ./storage-streaming
      dockerfile: Dockerfile
    environment:
      - APP_PORT=8080
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
    volumes:
      - ./storage-streaming:/app/
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "4000:27017"
    restart: always